rss:
  - id: swpc-alerts-rss
    url: https://services.swpc.noaa.gov/rss/alerts.xml
    tags: [space-weather, swpc, alerts]
  - id: swpc-news-rss
    url: https://services.swpc.noaa.gov/news/index.rss
    tags: [space-weather, swpc, news]
  - id: solarham
    url: https://www.solarham.net/rss.xml
    tags: [space-weather, solar]
  - id: nasa-news
    url: https://www.nasa.gov/news-release/feed/
    tags: [nasa, space]
  - id: livescience-space
    url: https://www.livescience.com/space/rss
    tags: [science, space]

api:
  # NOAA SWPC alerts (JSON) – table or dicts depending on endpoint
  - id: swpc-alerts-json
    url: https://services.swpc.noaa.gov/products/alerts.json
    parser: swpc_alerts
    tags: [space-weather, swpc, alerts]

  # NOAA SWPC planetary K index (JSON table)
  - id: swpc-kp-3day
    url: https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json
    parser: swpc_kp
    tags: [space-weather, kp]

  # USGS earthquakes – threshold in code (M>=5.5)
  - id: usgs-quakes
    url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson
    parser: usgs_quake
    tags: [earth, quake]

    api:
  - id: swpc-rtsw-plasma
    url: https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json
    parser: swpc_rtsw_plasma1d
    tags: [swpc, rtsw, plasma]

  - id: swpc-rtsw-mag
    url: https://services.swpc.noaa.gov/products/solar-wind/mag-1-day.json
    parser: swpc_rtsw_mag1d
    tags: [swpc, rtsw, mag]

  - id: swpc-ovation
    url: https://services.swpc.noaa.gov/json/ovation_aurora_latest.json
    parser: swpc_ovation_latest
    tags: [swpc, ovation, aurora]

  - id: swpc-geomag-3day
    url: https://services.swpc.noaa.gov/text/3-day-geomag-forecast.txt
    parser: swpc_geomag_3day_txt
    tags: [swpc, forecast, geomag]
