rss:
  - id: solarham
    url: https://www.solarham.net/rss.xml
    tags: [space-weather, solar]
  - id: livescience-space
    url: https://www.livescience.com/space/rss
    tags: [science, space]
  - id: nasa-news
    url: https://www.nasa.gov/news-release/feed/
    tags: [nasa, space]

api:
  - id: usgs-quakes
    url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson
    tags: [earth, quake]
    parser: usgs_quake  # special handler in code

rss:
  - id: swpc-alerts-rss
    url: https://services.swpc.noaa.gov/rss/alerts.xml
    tags: [space-weather, swpc, alerts]
  - id: swpc-news-rss
    url: https://services.swpc.noaa.gov/news/index.rss
    tags: [space-weather, swpc, news]

api:
  # NOAA SWPC Alerts (JSON) – recent alerts/advisories
  - id: swpc-alerts-json
    url: https://services.swpc.noaa.gov/products/alerts.json
    parser: swpc_alerts
    tags: [space-weather, swpc, alerts]

  # NOAA SWPC Kp (planetary K index, JSON Table) – useful headline metric
  - id: swpc-kp-3day
    url: https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json
    parser: swpc_kp
    tags: [space-weather, swpc, kp]

  # National Weather Service (NWS) – active alerts (needs User-Agent)
  - id: nws-alerts-active
    url: https://api.weather.gov/alerts/active
    parser: nws_alerts
    tags: [weather, alerts]
# You can add NOAA/SWPC JSON endpoints here later
