rss:
  - id: swpc-alerts-rss
    url: https://services.swpc.noaa.gov/rss/alerts.xml
    tags: [space-weather, swpc, alerts]
  - id: swpc-news-rss
    url: https://services.swpc.noaa.gov/news/index.rss
    tags: [space-weather, swpc, news]
  - id: solarham
    url: https://www.solarham.net/rss.xml
    tags: [space-weather, solar]
  - id: nasa-news
    url: https://www.nasa.gov/news-release/feed/
    tags: [nasa, space]
  - id: livescience-space
    url: https://www.livescience.com/space/rss
    tags: [science, space]

api:
  # NOAA SWPC alerts (JSON) – table or dicts depending on endpoint
  - id: swpc-alerts-json
    url: https://services.swpc.noaa.gov/products/alerts.json
    parser: swpc_alerts
    tags: [space-weather, swpc, alerts]

  # NOAA SWPC planetary K index (JSON table)
  - id: swpc-kp-3day
    url: https://services.swpc.noaa.gov/products/summary/planetary-k-index-3-day.json
    parser: swpc_kp
    tags: [space-weather, kp]

  # USGS earthquakes – threshold in code (M>=5.5)
  - id: usgs-quakes
    url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson
    parser: usgs_quake
    tags: [earth, quake]

  - id: swpc-rtsw-plasma
    url: https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json
    parser: swpc_rtsw_plasma1d
    tags: [swpc, rtsw, plasma]

  - id: swpc-rtsw-mag
    url: https://services.swpc.noaa.gov/products/solar-wind/mag-1-day.json
    parser: swpc_rtsw_mag1d
    tags: [swpc, rtsw, mag]

  - id: swpc-ovation
    url: https://services.swpc.noaa.gov/json/ovation_aurora_latest.json
    parser: swpc_ovation_latest
    tags: [swpc, ovation, aurora]

  - id: swpc-geomag-3day
    url: https://services.swpc.noaa.gov/text/3-day-geomag-forecast.txt
    parser: swpc_geomag_3day_txt
    tags: [swpc, forecast, geomag]

  # --- Additional SWPC text products (enable after parsers are added) ---
  - id: swpc-forecast-discussion
    url: https://services.swpc.noaa.gov/text/discussion.txt
    parser: swpc_discussion_txt
    tags: [swpc, discussion]
  
  - id: swpc-3-day-forecast
    url: https://services.swpc.noaa.gov/text/3-day-forecast.txt
    parser: swpc_3day_forecast_txt
    tags: [swpc, forecast]
  - id: swpc-advisory-outlook
    url: https://services.swpc.noaa.gov/text/advisory-outlook.txt
    parser: swpc_advisory_outlook_txt
    tags: [swpc, advisory, outlook]
  - id: swpc-report-geo-activity
    url: https://services.swpc.noaa.gov/text/weekly.txt
    parser: swpc_weekly_report_txt
    tags: [swpc, weekly, report]

api:
  - id: swpc-rtsw-plasma1d
    url: https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json
    parser: swpc_rtsw_plasma1d
    tags: [space-weather, solar-wind, nowcast]

  - id: swpc-rtsw-mag1d
    url: https://services.swpc.noaa.gov/products/solar-wind/mag-1-day.json
    parser: swpc_rtsw_mag1d
    tags: [space-weather, IMF, Bz, nowcast]

  - id: swpc-geomag-3day
    url: https://services.swpc.noaa.gov/text/3-day-geomag-forecast.txt
    parser: swpc_geomag_3day_txt
    tags: [forecast, geomagnetic]

  - id: swpc-ovation-latest
    url: https://services.swpc.noaa.gov/json/ovation_aurora_latest.json
    parser: swpc_ovation_latest
    tags: [aurora, ovation]