name: Gaia Eyes — Research Lane

on:
  schedule:
    - cron: "0 13 * * *"   # 13:00 UTC daily; adjust as needed
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run collector
        working-directory: bots/research_lane
        env:
          SUPABASE_REST_URL: ${{ secrets.SUPABASE_REST_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GAIA_TIMEZONE: ${{ secrets.GAIA_TIMEZONE }}
          HTTP_USER_AGENT: "GaiaEyesBot/1.0 (+https://gaiaeyes.com; gaiaeyes7.83@gmail.com)"
        run: python research_collector.py

  summarize:
    runs-on: ubuntu-latest
    needs: collect
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        working-directory: bots/research_lane
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv openai
      - name: Summarize new articles
        working-directory: bots/research_lane
        env:
          SUPABASE_REST_URL: ${{ secrets.SUPABASE_REST_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GAIA_OPENAI_MODEL: gpt-4o-mini
        run: python research_summarize.py

  publish:
    runs-on: ubuntu-latest
    needs: summarize
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        working-directory: bots/research_lane
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      - name: Post roundup to WordPress
        working-directory: bots/research_lane
        env:
          SUPABASE_REST_URL: ${{ secrets.SUPABASE_REST_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_STATUS: draft     # set to publish when you’re ready
          WP_CATEGORY_ID: ${{ secrets.WP_CATEGORY_ID }}
          WP_TAG_IDS: ${{ secrets.WP_TAG_IDS }}
        run: python research_wp_poster.py
