name: Research Spotlight
on:
  schedule:
    - cron: "45 18 * * *"   # later in the day
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_REST_URL: ${{ secrets.SUPABASE_REST_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      WP_BASE_URL:     ${{ secrets.WP_BASE_URL }}
      WP_USERNAME:     ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      SUMMARY_MODE: evergreen
      EVERGREEN_MODE: "1"
      RESEARCH_MAX_PER_RUN: "1"
      EVG_FETCH_LIMIT: "7"
      WP_CATEGORY_SLUG: research
      WP_TITLE_PREFIX: "Research Spotlight: "
      AUTO_POST: "1"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r bots/research_collector/requirements.txt
      - run: |
          python bots/research_collector/research_summarize.py
          python bots/research_collector/research_wp_poster.py