name: research-watch
on:
  schedule: [{cron: "20 12,18 * * *"}]  # 7:20am & 1:20pm CT (adjust)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install feedparser pydantic python-dateutil requests
      - run: pip install feedparser pydantic python-dateutil requests pillow
      - env:
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          RESEARCH_TOP_N: "3"
          RESEARCH_MIN_SCORE: "0.45"
          RESEARCH_RECENT_HOURS: "120"
          RESEARCH_FORCE_ONE: "1"
          RESEARCH_RENDER_MEDIA: "1"
        run: python -m bots.research_watch.run