name: WP — Publish Daily

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYY-MM-DD (optional; not used by poster, kept for parity)"
        required: false
      include_body:
        description: "Include full markdown body (true/false)"
        required: false
        default: "false"
  schedule:
    - cron: "20 14 * * *" # 14:20 UTC ~ 09:20 America/Chicago

jobs:
  media_sha:
    name: Resolve media repo SHA
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.pick.outputs.sha }}
    env:
      MEDIA_REPO_OWNER: ${{ secrets.MEDIA_REPO_OWNER }}
      MEDIA_REPO_NAME: ${{ secrets.MEDIA_REPO_NAME }}
    steps:
      - name: Validate repo env
        run: |
          test -n "${MEDIA_REPO_OWNER}" || (echo "MEDIA_REPO_OWNER not set" && exit 1)
          test -n "${MEDIA_REPO_NAME}"  || (echo "MEDIA_REPO_NAME not set" && exit 1)

      - name: Fetch latest SHA (shallow clone)
        run: |
          git clone --depth 1 https://github.com/${MEDIA_REPO_OWNER}/${MEDIA_REPO_NAME}.git repo
          cd repo
          git rev-parse HEAD > ../SHA

      - name: Export SHA
        id: pick
        run: |
          SHA="$(cat SHA)"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "Resolved media repo SHA: $SHA"

  publish:
    name: Publish to WordPress
    runs-on: ubuntu-latest
    needs: media_sha
    env:
      # --- Supabase ---
      SUPABASE_REST_URL: ${{ secrets.SUPABASE_REST_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GAIA_TIMEZONE: ${{ secrets.GAIA_TIMEZONE }}

      # --- Media CDN (versioned with resolved SHA) ---
      MEDIA_REPO_OWNER: ${{ secrets.MEDIA_REPO_OWNER }}
      MEDIA_REPO_NAME: ${{ secrets.MEDIA_REPO_NAME }}
      MEDIA_CDN_BASE: https://cdn.jsdelivr.net/gh/${{ secrets.MEDIA_REPO_OWNER }}/${{ secrets.MEDIA_REPO_NAME }}@${{ needs.media_sha.outputs.sha }}/images

      # --- WordPress creds ---
      WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      WP_ALT_USERNAME: ${{ secrets.WP_ALT_USERNAME }}

      # --- Posting controls ---
      WP_STATUS: publish                      # change to 'draft' during testing
      WP_CATEGORY_ID: ${{ secrets.WP_CATEGORY_ID }}     # optional
      WP_TAG_IDS: ${{ secrets.WP_TAG_IDS }}             # optional comma-separated IDs

      # Featured image from backgrounds in media repo
      WP_FEATURED_SOURCE: bg                  # 'bg' | 'caption' | 'none'
      WP_FEATURED_BG_KIND: square            # 'square' | 'tall' | 'wide'
      WP_FEATURED_CREDIT: Image: Gaia Eyes backgrounds

      # Body/TOC options
      WP_INLINE_IMAGES: "true"                # include tall images as a gallery
      WP_UPLOAD_INLINE: "false"               # hotlink tall images; set "true" to upload to WP media
      WP_ADD_TOC: "false"                     # optional table of contents
      WP_INCLUDE_BODY: ${{ github.event.inputs.include_body || 'false' }}

      # Optional CTA (HTML) appended at end of post
      WP_CTA_HTML: ${{ secrets.WP_CTA_HTML }}

      # Optional UTM query to append to image URLs
      UTM_QUERY: "?utm_source=wp&utm_medium=post&utm_campaign=daily-earthscope"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show media base (debug)
        run: |
          echo "MEDIA_CDN_BASE=${MEDIA_CDN_BASE}"
          echo "Resolved media SHA=${{ needs.media_sha.outputs.sha }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: bots/earthscope_post
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Publish to WordPress
        working-directory: bots/earthscope_post
        run: python wp_poster.py
